site_name: backstage-app
site_description: backstage-app 애플리케이션 공식 문서

plugins:
  - techdocs-core

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md