apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: testservice
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${{ values.port }}
  type: ClusterIP
